USE master
GO

CREATE DATABASE AtvBD
GO

USE AtvBD
GO

CREATE TABLE CLIENTES(
Id INT IDENTITY,
Nome NVARCHAR(200),
Usuario NVARCHAR(50) NOT NULL UNIQUE,
Telefone NVARCHAR(20) NOT NULL,
Email NVARCHAR(200) NOT NULL UNIQUE,
DtCadastro NVARCHAR(20) NOT NULL)
GO

DECLARE @Nome AS NVARCHAR(200)='TESTE1'
DECLARE @Usuario AS NVARCHAR(50)='TESTE1'
DECLARE @Telefone AS NVARCHAR(20)='(11)1234-5678'
DECLARE @Email AS NVARCHAR(200)='TESTE@TESTE.COM'
DECLARE @DtCliente AS NVARCHAR(20)='12/12/2012'
INSERT INTO CLIENTES(Nome,Usuario,Telefone,Email,DtCadastro)
VALUES(@Nome,@Usuario,@Telefone,@Email,@DtCliente)
go
SELECT * FROM CLIENTES
go


CREATE TABLE PRODUTO(
Id INT IDENTITY,
Nome NVARCHAR(200) NOT NULL,
Tipo NVARCHAR(50) NOT NULL,
UnMedida NVARCHAR(2) NOT NULL,
Quantidade NVARCHAR(5) NOT NULL)
GO
