USE master
GO

CREATE DATABASE AtividadeBD
GO

USE AtividadeBD
GO

CREATE TABLE CLIENTES(
Id INT IDENTITY,
Nome NVARCHAR(200),
Usuario NVARCHAR(50) NOT NULL UNIQUE,
Telefone NVARCHAR(20) NOT NULL,
Email NVARCHAR(200) NOT NULL UNIQUE,
DtCadastro NVARCHAR(20) NOT NULL)
GO

DECLARE @Nome AS NVARCHAR(200)='CÁSSIO'
DECLARE @Usuario AS NVARCHAR(50)='CRSP'
DECLARE @Telefone AS NVARCHAR(20)='(11)4455-5566'
DECLARE @Email AS NVARCHAR(200)='CRSP@CRSP.COM'
DECLARE @DtCliente AS NVARCHAR(20)='12/12/2012'
INSERT INTO CLIENTES(Nome,Usuario,Telefone,Email,DtCadastro)
VALUES(@Nome,@Usuario,@Telefone,@Email,@DtCliente)
go
SELECT * FROM CLIENTES
go

drop table CLIENTES